FROM python:3.12-bookworm

# 작업 디렉토리 설정
WORKDIR /code

# ./requirements.txt 를 /code/requirements.txt 로 복사
COPY ./requirements.txt /code/requirements.txt

# JAVA 설치 추가
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    gcc \
    poppler-utils \
    libgl1-mesa-glx \
    openjdk-17-jdk \
    && apt-get clean

# JAVA 경로 설정
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# requirements.txt 를 보고 모듈 전체 설치(-r)
RUN pip install --no-cache-dir -r /code/requirements.txt
RUN pip install requests

# 애플리케이션 코드 복사

COPY ./app /code/app

# 실행
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
